### ISSUE TITLE
Set up appveyor to build Windows wheels and upload them to PyPI

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.proxy#24]
This needs

- [x] a copy of appveyor.yml from zope.interface or similar
- [x] someone with an Appveyor account (e.g. me) to enable this project
- [x] encrypted PyPI upload credentials in the appveyor.yml (no change required from the copy in zope.interface if I'm the one who enables the Appveyor account)
- [x] grant **zope.wheelbuilder** PyPI rights
- [x] push the appveyor.yml commit to master
- [x] (optionally) a push of a temporary branch that builds and uploads zope.proxy 4.3.0 wheels

**Comment by dataflake** [comment]
@mgedmin Hi Marius, I need to know the zope.wheelbuilder PyPI credentials to set up Appveyor builds for some of the packages that still need it. You can gpg-encrypt it to jens@netz.ooo and share it here.

**Comment by mgedmin** [comment]
@tseaver, are you fine with me sharing zope.wheelbuilder credentials with Jens?

@dataflake, just to confirm, your GPG key is rsa4096/AD96F6F572A6D22A, with fingerprint 3CA2 C229 EC7A 8AB0 EE98  D431 AD96 F6F5 72A6 D22A?

**Comment by dataflake** [comment]
@mgedmin, the GPG key is correct.

**Comment by dataflake** [comment]
@mgedmin I'm guessing Tres is on vacation, but I would like to get this done. The fact that I am co-owner of the zopefoundation GitHub organization and have update rights on all Zope2-related eggs on PyPI should really be enough proof that sharing this password with me is OK.

**Comment by tseaver** [comment]
@mgedmin I'm fine with giving @dataflake the PyPI credentials for zope.wheelbuilder.  Apologies for the delay in replying..

**Comment by mgedmin** [comment]
I just want to make sure everyone who currently has the credentials knows who else has them, in case we have to change and re-distribute the password again.

Now to remember how to use gpg, *sigh*

**Comment by dataflake** [comment]
``gpg -ear jens@netz.ooo /path/to/file`` or
``cat /path/to/file | gpg -ear jens@netz.ooo``

**Comment by mgedmin** [comment]
Here's the password, encrypted for @dataflake's key:

```
-----BEGIN PGP MESSAGE-----

hQIMAwIKiAeWWRiNAQ/+KQcxeiVdeYLcZ4+QfRbcNwc2l0tBovkGxVpRthAhxa7o
1YMXT7KHifcNWjMuCX6r+L7nwZg9Mo1/77b3u8AvhdZEroKgrN/npiXZQTmbzgUn
fc+GFMn7M870yJYxYG3vN5HDlwsK/ZkDCWgt/xBeROH9Uc3juEXaBPsUrLWGm3ye
rXpcfBUd7aEYLaDsAE++MMmcxf0PWoGWqf6gjQNPuYvDlDI04L5+QX9leVB0zW80
r0qn3lB0zsrWLE5L7j2KJKUpUS5MMKf6DwweRN9+tz2BGUXW3ZAYFMPPQMWhKWXt
PFE9vWBmFg1mvsap9IIqVeEjnsP4+r99edF9g5vvB3ll7GICb8Wd+vori7tb5UeV
ehxGG1oGbOm74f/BPDm4MRBY2IwhFLdzTnab29M6euSobU+J8iXWArTdK8foFvCi
Cx7Zl9vbV0XCZgYwWdCiV/YyDfFgYKqL1il7PYAtaGnlDf1KMc59UzDocjGk2IjM
RjwMIlhtFYcdSZZDqkfbSUup7lEcq3AIO8/ynknmlF9UD03+8PCdYrX9Z5I4a6ar
yetekuyQFuV40PNz7ATiGbONxbJOnkbM4UGOtbQVxMkAkhflxy6FWbch0nRl7Bex
g/px2m2Iz+GVO4eU99lVP3se9kR4bckHVMH/h/OofU63zR4oEIT3CIbEe0fikcuF
AQ4DmlT1velc5vUQA/9OAE/r3YkKZufXgi7C87vSXm+PoHXujwQ4IfCGnQp1yOdD
v8tr2vM2X4mWdg1VJWshC0wgYtlTX25f3fV2b8YvFhedoNGW/jymcINIfcAUZlpZ
2i6Ug1qbTdo44yrnMxtao4UVvreNuKSUj8SdbULm/m4w4lWeX/OdbWsdil2scgP9
ES1WtAxX8LkWW1Lxj6sibpwqNjcfOx8fyPQ/S2F80ke3l6Xo/3bBE76qIIOF+fE4
WabxB2Ek2D3R5CS2ije+sNXEcC/MNQ8MHVyehze4CxYGpBh4i/KKKZdlxnz5wTQW
tRXLXMIJiZVQ/sAm1DAH1/VXNhjlCmQC46OoNY0346fSRgHiTmNNTWW/indqHWhp
FkVKnevyUyfXf8OZHJgee5Zlby4JS9FK1OhXPztOruOLSD8IO6bEnN2vDGmtUU1f
RWlGImXLbWg=
=kDhv
-----END PGP MESSAGE-----
```

**Comment by dataflake** [comment]
@mgedmin Thank you, it works. Now back to Appveyor...
