### ISSUE TITLE
Compiler warning (-Wint-conversion)

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.proxy#30]
Noticed this scrolling past during a `buildout` run on Ubuntu 19.04:

```
src/zope/proxy/_zope_proxy_proxy.c: In function ‘wrap_setattro’:
src/zope/proxy/_zope_proxy_proxy.c:315:16: warning: returning ‘void *’ from a function with return type ‘int’ makes integer from pointer without a cast [-Wint-conversion]
         return NULL;
                ^~~~
```

**Comment by mgedmin** [comment]
This looks like an actual bug introduced in commit 43814c7caaa0c377dac4f06067080d7916fa3980: the `tp_setattro` callback is supposed to return -1 on error.

https://github.com/zopefoundation/zope.proxy/blob/cd9691fd0665b7fec6b70ba7de87278c36986672/src/zope/proxy/_zope_proxy_proxy.c#L308-L316

**Comment by jamadden** [comment]
That’s definitely a bug! Thanks for finding it!  I think the goto would be fine.
