### ISSUE TITLE
Installation breaks on current setuptools version

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.proxy#38]
`ImportError: cannot import name 'Feature' from 'setuptools' `

**Comment by mgedmin** [comment]
This is [fixed on master](https://github.com/zopefoundation/zope.proxy/commit/1173e599cea5c61cf61128e3470eb6e673d3d899), so all we need is a new release (and mention the Feature drop in the changelog).

**Comment by mgedmin** [comment]
4.3.4 pushed to PyPI, we're waiting for CI builders to create all the wheels.

(I've also updated .travis.yml to build Python 3.8 wheels for Mac OS.)

**Comment by icemac** [comment]
@mgedmin Thank you very much, I did even not hope that is was so easy.
