### ISSUE TITLE
 zope.proxy breaks `__float__` and `__int__`

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.proxy#4]
In https://bugs.launchpad.net/zope.proxy/+bug/1263115, @mgedmin reported:

> I'm a bit pressed for time, but basically you take a string like '14', wrap it with a zope.proxy-based proxy, then try to call float() or into() on the proxy -- you'll get a type error. Calling int()/float() directly on the value obviously succeeds.

**Comment by tseaver** [comment]
Maybe the coercion methods are only looked up on the type now?  (as for `__unicode__` after http://bugs.python.org/issue2517).

**Comment by jamadden** [comment]
Somewhat ironically, this does work in the pure-Python version.
