### ISSUE TITLE
Uses deprecated API PyEval_CallObjectWithKeywords, raises warnings under 3.9 and 3.10

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.proxy#43]
As described in https://github.com/zopefoundation/zope.container/issues/40, this project contains a use of a deprecated API (`PyEval_CallObjectWithKeywords`) that could be removed soon:

https://github.com/zopefoundation/zope.proxy/blob/9424b6e6a31ab9338ffc6e1effaf5a50cdfacb10/src/zope/proxy/_zope_proxy_proxy.c#L377-L382

I think there's a simple drop-in replacement API, I remember running into this as a warning under 3.9 and making a change in…some project.

**Comment by tseaver** [comment]
Via PR #65.
