### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [zopefoundation/zope.proxy#44]
Problem
---------
On aarch64, pip install zope.proxy builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install zope.proxy should download the wheels from pypi

@dataflake , please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by jamadden** [comment]
This will eventually be handled as part of the migration from Travis CI to GitHub actions.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.proxy/4.4.0/#files. The wheels should show up in some minutes.
