### ISSUE TITLE
test_proxy.py still uses assert assertRaisesRegexp, removed in Python 3.12

### ISSUE THREAD

**Issue by doko42** [zopefoundation/zope.proxy#63]
test_proxy.py still uses assert assertRaisesRegexp, removed in Python 3.12, letting the test fail

--- a/src/zope/proxy/tests/test_proxy.py
+++ b/src/zope/proxy/tests/test_proxy.py
@@ -48,7 +48,7 @@ class PyProxyBaseTestCase(unittest.TestC
     # coping with Python 2 not having the Regex spelling variant
     assertRaisesRegex = getattr(
         unittest.TestCase, 'assertRaisesRegex',
-        getattr(unittest.TestCase, 'assertRaisesRegexp', None))
+        getattr(unittest.TestCase, 'assertRaisesRegex', None))
 
     def _getTargetClass(self):
         from zope.proxy import PyProxyBase

**Comment by icemac** [comment]
Thank you for reporting, I fixed the issue.
